### ISSUE TITLE
improve doc

### ISSUE THREAD

**Issue by Vadorequest** [angular-ui/ui-event#3]
Please improve the documentation with an example of all usages of `ui-event`. :)

**Comment by PowerKiKi** [comment]
This project strongly rely on contributions from its users. If you think something is missing, please create a PR to add it.

**Comment by Vadorequest** [comment]
A complete stranger to the project isn't supposed to write the doc about it
nor how to use it.
Le 12 janv. 2016 02:35, "Adrien Crivelli" notifications@github.com a
écrit :
